### ISSUE TITLE
Button tooltips

### ISSUE THREAD

**Issue by APXEOLOG** [NodeBB/nodebb-plugin-composer-redactor#3]
Hi! There are tootips in the official redactor http://imperavi.com/redactor/
Why don't we have them?

**Comment by drewdotpro** [comment]
Thank you for your input! =) 
Redactor is a new addition to the NodeBB package. There is lots more to do. If you're a developer please feel free to add button tooltips and send a pull request.

**Comment by julianlam** [comment]
It's odd though, I noticed this as well. I thought the tooltips came with the default settings...

**Comment by philburr** [comment]
The problem with the tooltip is the z-index.
nodebb-plugin-composer-default/static/less/composer.less:
.composer {
    z-index: 10000;
}

nodebb-plugin-composer-redactor/static/less/redactor.less:
.redactor-dropdown {
    z-index: 1052;
}
#redactor-modal {
    z-index:1053;
}

Redactor styling has quite a few things that end up underneath the composer area because of z-order.  It's pretty easy to fix...

**Comment by drewdotpro** [comment]
Should be sorted in 1.0.5
