### ISSUE TITLE
File Upload Error Handler

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/nodebb-plugin-composer-redactor#74]
Hello Devs,

Upon file upload error (for example: file too big, Invalid mime type), redactor fails and does not recover. To reproduce - add a hook with:

`{ "hook": "filter:uploadFile",          "method": "myUploadFile", "priority": 6 }
`
In myUploadFile just return an error for example:

`return callback(Error('myError'));
`
Redactor fails in line 10697 here:

`xhr.send(formData);
`
Since errors are not handled , JS stops dead on the spot. Furthermore, the user does not get any feedback of the error, although the xhr packet does contain an error string. With that, the only way to recover is to close the editor and re-open it.

The fix in Redactor might be simple to code: basically capturing the error and toasting a message. 
Note I believe the same issue plagues image upload as well.

Kindly let me know should you need further information,

**Comment by julianlam** [comment]
Yeek -- that's redactor code. Unfortunately we can't edit this because that's vendor code, and we also don't support it for that same reason.

Sadly because we cannot update to latest Redactor, I recommend people try to work around the issue for now, until an alternative (Quill composer being in active development at the moment) is completed.

**Comment by PostMidnight** [comment]
Wow too bad. In nodebb-quill we had a similar issue but it was resolved with an error handler I remember. Will you have some time to get back to Quill development soon? the plugin is almost release worthy.
